.

diff --git a/.github/workflows/deploy-pkgdown.yaml b/.github/workflows/deploy-pkgdown.yaml
--- a/.github/workflows/deploy-pkgdown.yaml
+++ b/.github/workflows/deploy-pkgdown.yaml
@@ -3,7 +3,7 @@
 on:
   push:
     branches:
-      - master  # o main, dependiendo de tu rama principal
+      - master  # Asegúrate de que esta sea tu rama principal (o 'main')
 
 name: Deploy pkgdown site
 
@@ -21,7 +21,7 @@ jobs:
 
       - uses: r-lib/actions/setup-r@v2
         with:
-          r-version: 'release' # Puedes especificar una versión como '4.3.0'
+          r-version: 'release' # Puedes especificar una versión como '4.3.0' si lo necesitas
 
       - uses: r-lib/actions/setup-r-dependencies@v2
         with:
@@ -41,11 +41,15 @@ jobs:
         run: |
           R -e 'pkgdown::build_site()'
 
+      - name: List files in workspace for debugging
+        run: |
+          echo "Listing contents of /github/workspace:"
+          ls -R /github/workspace
+          echo "Listing contents of /github/workspace/docs:"
+          ls -R /github/workspace/docs || echo "docs directory not found or empty." # Esto nos ayudará a confirmar si 'docs' existe
+
       - name: Setup Pages
         uses: actions/configure-pages@v4
-
-      - name: List files in workspace
-        run: ls -R /github/workspace
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
