.

diff --git a/.github/workflows/deploy-pkgdown.yaml b/.github/workflows/deploy-pkgdown.yaml
--- a/.github/workflows/deploy-pkgdown.yaml
+++ b/.github/workflows/deploy-pkgdown.yaml
@@ -3,7 +3,7 @@
 on:
   push:
     branches:
-      - master  # Asegúrate de que esta sea tu rama principal (o 'main')
+      - master
 
 name: Deploy pkgdown site
 
@@ -21,14 +21,13 @@ jobs:
 
       - uses: r-lib/actions/setup-r@v2
         with:
-          r-version: 'release' # Puedes especificar una versión como '4.3.0' si lo necesitas
+          r-version: '4.3.0'
 
       - uses: r-lib/actions/setup-r-dependencies@v2
         with:
           packages: |
             pkgdown
-            # Aquí añade cualquier otra dependencia de tu paquete que pkgdown necesite
-            # Por ejemplo, si tu paquete usa data.table, ponlo aquí
+             sf
           extra-packages: |
             remotes
 
@@ -46,7 +45,7 @@ jobs:
           echo "Listing contents of /github/workspace:"
           ls -R /github/workspace
           echo "Listing contents of /github/workspace/docs:"
-          ls -R /github/workspace/docs || echo "docs directory not found or empty." # Esto nos ayudará a confirmar si 'docs' existe
+          ls -R /github/workspace/docs || echo "docs directory not found or empty."
 
       - name: Setup Pages
         uses: actions/configure-pages@v4
@@ -54,7 +53,7 @@ jobs:
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: 'docs' # Asegúrate de que esta sea la carpeta donde pkgdown genera el sitio
+          path: 'docs'
 
       - name: Deploy to GitHub Pages
         id: deployment
